name: Keboola Component Build & Deploy Pipeline
on:
  push:
    branches-ignore:
      - main
    tags:
      - "*"

concurrency: ci-${{ github.ref }}

jobs:
  ci:
    uses: keboola/component-ci/.github/workflows/component-pipeline.yml@master
    with:
      app_id: COOKIECUTTER_DEV_PORTAL_VENDOR_NAME.COOKIECUTTER_DEV_PORTAL_COMPONENT_ID
      vendor: COOKIECUTTER_DEV_PORTAL_VENDOR_NAME
      # For multi-stage Docker builds, uncomment:
      # test_build_target: test
      # docker_build_target: production
    secrets: inherit
